### ISSUE TITLE
Export de la liste des consommateurs par contrats

### ISSUE THREAD

**Issue by ShauniArima** [aliceb64/amapj#12]
ETQ Alice
JE SOUHAITE obtenir la liste des consommateurs par contrats et leurs produits associés
AFIN D' obtenir la liste d'émargement et de la donner au producteur concerné

**Comment by Dibion** [comment]
Déjà disponible sur Amapj, compte référent, via les "livraisons d'un producteur", on peut export un excel avec la liste des utilisateurs ayant un contrat avec le producteur correspondant.

<img width="514" alt="export-emargement" src="https://user-images.githubusercontent.com/32643108/31440409-0bdc7692-ae90-11e7-8fb6-a844a534d472.PNG">
