### ISSUE TITLE
Définition base de données

### ISSUE THREAD

**Issue by ShauniArima** [aliceb64/amapj#4]
ETQ développeur
JE SOUHAITE mettre en place une base de données externe
AFIN DE faciliter la gestion des données de la solution

**Comment by ShauniArima** [comment]
Mise en place de SQL complexe.
Solution possible :
```
Utilisation de HSQL DB !
```

**Comment by vgestas** [comment]
Utilisation de HSQLDB (imposé par l'application) et en interne car OVH ne permet pas de connexion SSH pour installer le SGBD en externe

**Comment by ShauniArima** [comment]
Abandon mise en place MySQL au profit de HSQLBD. 
`Déja pris en compte par AmapJ`
